# Don't merge into main - this is just for dry-running our setup
#
class AddSilverLakeBandAndSongs < ActiveRecord::Migration[8.0]
  def up
    slb = Band.create(name: "Silver Lake Band")
    sl1 = List.create(band_id: slb.id, name: "Best Stuff 1", notes: "Started working this 2024 Q4")
    s01 = Song.create(band_id: slb.id, title: "Down by the Water", performer: "The Decembrists", intro: "Drum: 2 measures")
    s02 = Song.create(band_id: slb.id, title: "Breakfast in America", performer: "Supertramp", intro: "Bass and Keyboard: 4 measures slow")
    s03 = Song.create(band_id: slb.id, title: "Like a Hurricane", performer: "Neil Young", intro: "Drum count; Keyboard and Harmonica")
    s04 = Song.create(band_id: slb.id, title: "Manic Monday", performer: "The Bangles", intro: "Drum count")
    s05 = Song.create(band_id: slb.id, title: "Californication", performer: "Red Hot Chili Peppers", intro: "Bass and Keyboard (Casio organ)")
    s06 = Song.create(band_id: slb.id, title: "Dead Flowers", performer: "The Rolling Stones", intro: "Drum count")
    s07 = Song.create(band_id: slb.id, title: "Running on Empty", performer: "Jackson Browne", intro: "Drum count: Bass and Keyboard")
    s08 = Song.create(band_id: slb.id, title: "Better Man", performer: "Pearl Jam", intro: "Drum count: Guitar and Keyboard")
    s09 = Song.create(band_id: slb.id, title: "Southern Cross", performer: "CSN", intro: "Drum count")
    s10 = Song.create(band_id: slb.id, title: "Have you Ever Seen the Rain", performer: "CCR", intro: "Drum count")
    s11 = Song.create(band_id: slb.id, title: "I'm Eighteen", performer: "Alice Cooper", intro: "Drum count")
    s12 = Song.create(band_id: slb.id, title: "Vacation", performer: "The Go-Gos", intro: "Drum count: Keyboard and Drum")
    s13 = Song.create(band_id: slb.id, title: "Big Empty", performer: "Stone Temple Pilots", intro: "Keyboard")
    s14 = Song.create(band_id: slb.id, title: "Lonely Boy", performer: "The Black Keys", intro: "Drum count")
    s15 = Song.create(band_id: slb.id, title: "Wagon Wheel", performer: "Old Crow Medicine Show", intro: "Drum count")
    s16 = Song.create(band_id: slb.id, title: "Keep on Rocking in the Free World", performer: "Neil Young", intro: "Drum count")
    ListSong.create(list_id: sl1.id, song_id: s01.id, position: 1)
    ListSong.create(list_id: sl1.id, song_id: s02.id, position: 2)
    ListSong.create(list_id: sl1.id, song_id: s03.id, position: 3)
    ListSong.create(list_id: sl1.id, song_id: s04.id, position: 4)
    ListSong.create(list_id: sl1.id, song_id: s05.id, position: 5)
    ListSong.create(list_id: sl1.id, song_id: s06.id, position: 6)
    ListSong.create(list_id: sl1.id, song_id: s07.id, position: 7)
    ListSong.create(list_id: sl1.id, song_id: s08.id, position: 8)
    ListSong.create(list_id: sl1.id, song_id: s09.id, position: 9)
    ListSong.create(list_id: sl1.id, song_id: s10.id, position: 10)
    ListSong.create(list_id: sl1.id, song_id: s11.id, position: 11)
    ListSong.create(list_id: sl1.id, song_id: s12.id, position: 12)
    ListSong.create(list_id: sl1.id, song_id: s13.id, position: 13)
    ListSong.create(list_id: sl1.id, song_id: s14.id, position: 14)
    ListSong.create(list_id: sl1.id, song_id: s15.id, position: 15)
    ListSong.create(list_id: sl1.id, song_id: s16.id, position: 16)
  end
end
